# Generated by Django 5.2.4 on 2025-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_created_at_task_updated_at_alter_task_deadline_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["last_name"]},
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
