# Generated by Django 5.2.4 on 2025-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("wfr", "Waiting for Review"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
