# Generated by Django 5.2.4 on 2025-08-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_is_complete_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="description",
        ),
    ]
