# Generated by Django 5.2.4 on 2025-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_remove_position_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("reviewing", "Reviewing"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
