# Generated by Django 4.2.11 on 2026-02-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
